# Setup
title:'周大胖的技术博客'
subtitle:'记录技术，记录生活点滴'
description:'涉猎的主要编程语言为 Python、Rust、C/C++、领域涵盖爬虫深度学习、图像处理、自然语言处理等'
email:18328062372@163.com
url:https://Sammul40619.github.io
avatar:/avatar.jpeg
cover_image:/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag

logo: logo.png


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
gitalk:
  clientID: f0aaf85ff65877ef4050
  clientSecret: 27ac33e41de0e890c45b33da27e27334f75b6316
  repo: Sammul40619.github.io
  owner: Sammul40619
  
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-XXXXXXX-X
  
author:
  name: Songzi Vong
  url: https://github.com/Sammul40619/
  email: 18328062372@163.com
